# Tiny VGG Multi-Model Training Notebook

This notebook trains **three different CNN architectures with different layer orders** for the CNN Explainer project and exports all of them in a frontend-friendly format.

The default set covers three different depths:

- **Compact 7-layer**: a Conv → Pool → ReLU style order
- **Balanced 12-layer**: a mixed Conv / Pool / ReLU order
- **Deep 17-layer**: a deeper mixed-order CNN with three pooling stages

The notebook will:

1. mount Google Drive and prepare the dataset,
2. define several different architectures,
3. train and evaluate each model,
4. export each one to TensorFlow.js,
5. write a minimal `model-index.json` manifest for the website selector.

> Task 6.1: the examples below now vary both **layer order** and the **number of convolution kernels**. The number of kernels is the number of filters/nodes shown in each convolutional feature layer, not the spatial kernel size.

> Important: TensorFlow.js `.bin` files are raw weight shards. They do not contain layer names, layer order, tensor names, tensor shapes, or model topology. The website can derive architecture from `model.json`; it cannot derive architecture from `.bin` alone.

In [ ]:
# Colab / environment setup
from pathlib import Path
import json
import os
import re
import shutil
import subprocess
import sys
import zipfile
from glob import glob
from time import time

try:
    from google.colab import drive  # type: ignore
    IN_COLAB = True
except ImportError:
    IN_COLAB = False

if IN_COLAB:
    # Keep TensorFlow, TensorFlow.js converter, and TensorFlow Decision Forests ABI-compatible.
    # Run this before TensorFlow is imported. If TensorFlow was already imported, restart the runtime first.
    subprocess.run([
        sys.executable,
        '-m',
        'pip',
        'install',
        '-q',
        '--upgrade',
        'tensorflow==2.19.0',
        'tensorflowjs==4.22.0',
        'tensorflow-decision-forests==1.12.0',
    ], check=True)

import numpy as np
import pandas as pd
import tensorflow as tf

from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Conv2D, Activation, MaxPool2D, AveragePooling2D, Flatten, Dense
from tensorflow.keras.callbacks import EarlyStopping, ModelCheckpoint

print('TensorFlow:', tf.__version__)

if IN_COLAB:
    drive.mount('/content/drive')
    DRIVE_PROJECT_DIR = Path('/content/drive/MyDrive/CNN')
    DATA_ZIP = DRIVE_PROJECT_DIR / 'data.zip'
    WORKDIR = Path('/content/tiny-vgg')
else:
    WORKDIR = Path.cwd()
    DRIVE_PROJECT_DIR = WORKDIR
    DATA_ZIP = WORKDIR / 'data.zip'

WORKDIR.mkdir(parents=True, exist_ok=True)

print('Working directory:', WORKDIR)
print('Project directory:', DRIVE_PROJECT_DIR)
print('Data zip:', DATA_ZIP)
print('Data zip exists:', DATA_ZIP.exists())

TensorFlow: 2.19.0

ValueError: mount failed

## Data Setup

This notebook expects the same dataset layout used by `tiny-vgg.py`.

Preferred layout after extraction:

```text
tiny-vgg/
  data/
    class_dict_10.json
    val_class_dict_10.json
    class_10_train/
    class_10_val/
```

If only `data.zip` exists, the next cell extracts it.

In [ ]:
DATA_DIR = WORKDIR / 'data'

if not DATA_ZIP.exists():
    raise FileNotFoundError(f'Could not find {DATA_ZIP}')

if not DATA_DIR.exists():
    with zipfile.ZipFile(DATA_ZIP, 'r') as zf:
        zf.extractall(WORKDIR)
    print('Extracted:', DATA_ZIP)

print('DATA_DIR exists:', DATA_DIR.exists())
if DATA_DIR.exists():
    print('Data directory:', DATA_DIR)

Extracted: /content/drive/MyDrive/CNN/data.zip
DATA_DIR exists: True
Data directory: /content/tiny-vgg/data

In [ ]:
# Shared hyperparameters
WIDTH = 64
HEIGHT = 64
NUM_CLASS = 10
FILTERS = 10
EPOCHS = 25
PATIENCE = 8
LR = 1e-3
BATCH_SIZE = 64
SHUFFLE_BUFFER = 1000
# HIDDEN_DENSE_UNITS = [16, 8]
HIDDEN_DENSE_UNITS = [64, 32]
# HIDDEN_DENSE_UNITS = [128, 64]

MODEL_ROOT = WORKDIR / 'trained_models'
TFJS_ROOT = WORKDIR / 'frontend_models'
MODEL_ROOT.mkdir(parents=True, exist_ok=True)
TFJS_ROOT.mkdir(parents=True, exist_ok=True)

In [ ]:
# Dataset metadata
class_dict_path = DATA_DIR / 'class_dict_10.json'
val_class_dict_path = DATA_DIR / 'val_class_dict_10.json'

assert class_dict_path.exists(), f'Missing {class_dict_path}'
assert val_class_dict_path.exists(), f'Missing {val_class_dict_path}'

with open(class_dict_path, 'r') as f:
    tiny_class_dict = json.load(f)
with open(val_class_dict_path, 'r') as f:
    tiny_val_class_dict = json.load(f)

train_pattern = str(DATA_DIR / 'class_10_train' / '*' / 'images' / '*.JPEG')
val_pattern = str(DATA_DIR / 'class_10_val' / 'val_images' / '*.JPEG')
test_pattern = str(DATA_DIR / 'class_10_val' / 'test_images' / '*.JPEG')

print('Train images:', len(glob(train_pattern)))
print('Val images:', len(glob(val_pattern)))
print('Test images:', len(glob(test_pattern)))

Train images: 5000
Val images: 250
Test images: 250

In [ ]:
def process_path_train(path):
    path = path.numpy()
    image_name = os.path.basename(path.decode('ascii'))
    label_name = re.sub(r'(.+)_\d+\.JPEG', r'\1', image_name)
    label_index = tiny_class_dict[label_name]['index']

    label = tf.one_hot(indices=[label_index], depth=NUM_CLASS)
    label = tf.reshape(label, [NUM_CLASS])

    img = tf.io.read_file(path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.convert_image_dtype(img, tf.float32)
    img = tf.image.resize(img, [WIDTH, HEIGHT])
    return img, label


def process_path_test(path):
    path = path.numpy()
    image_name = os.path.basename(path.decode('ascii'))
    label_index = tiny_val_class_dict[image_name]['index']

    label = tf.one_hot(indices=[label_index], depth=NUM_CLASS)
    label = tf.reshape(label, [NUM_CLASS])

    img = tf.io.read_file(path)
    img = tf.image.decode_jpeg(img, channels=3)
    img = tf.image.convert_image_dtype(img, tf.float32)
    img = tf.image.resize(img, [WIDTH, HEIGHT])
    return img, label


def build_dataset(file_pattern, mode='train'):
    ds = tf.data.Dataset.list_files(file_pattern, shuffle=(mode == 'train'))

    if mode == 'train':
        mapper = lambda path: tf.py_function(process_path_train, [path], [tf.float32, tf.float32])
    else:
        mapper = lambda path: tf.py_function(process_path_test, [path], [tf.float32, tf.float32])

    ds = ds.map(mapper, num_parallel_calls=tf.data.AUTOTUNE)
    ds = ds.map(lambda x, y: (tf.ensure_shape(x, [WIDTH, HEIGHT, 3]), tf.ensure_shape(y, [NUM_CLASS])))

    if mode == 'train':
        ds = ds.shuffle(SHUFFLE_BUFFER)

    ds = ds.batch(BATCH_SIZE)
    ds = ds.prefetch(tf.data.AUTOTUNE)
    return ds


train_dataset = build_dataset(train_pattern, mode='train')
val_dataset = build_dataset(val_pattern, mode='val')
test_dataset = build_dataset(test_pattern, mode='test')

## Model Definitions

Each entry below defines a different network depth. They all keep the same input size, class count, and number of channels per feature layer so the website can still render them consistently.

In [ ]:
# Task 3 at lines 446-467: define the three trained demonstration architectures
# that the website will later switch between for 7-layer, 12-layer, and 17-layer comparisons.
MODEL_SPECS = [
    {
        'id': 'compact-7',
        'label': 'Compact 9-layer',
        'filters': 6,
        'hidden_dense_units': HIDDEN_DENSE_UNITS,
        'layer_plan': [
            'conv', 'relu',
            'conv', 'sigmoid',
            'avg_pool',
        ],
    },
    {
        'id': 'balanced-12',
        'label': 'Balanced 14-layer',
        'filters': 10,
        'hidden_dense_units': HIDDEN_DENSE_UNITS,
        'layer_plan': [
            'conv', 'relu',
            'conv', 'relu',
            'avg_pool',

            'conv', 'relu',
            'conv', 'relu',
            'max_pool',
        ],
    },
    {
        'id': 'deep-17',
        'label': 'Deep 19-layer',
        'filters': 14,
        'hidden_dense_units': HIDDEN_DENSE_UNITS,
        'layer_plan': [
            'conv', 'relu',
            'conv', 'relu',
            'avg_pool',

            'conv', 'relu',
            'conv', 'relu',
            'max_pool',

            'conv', 'relu',
            'conv', 'relu',
            'avg_pool',
        ],
    },
]

def summarize_plan(layer_plan, hidden_dense_units):
    conv_count = layer_plan.count('conv')
    relu_count = layer_plan.count('relu')
    sigmoid_count = layer_plan.count('sigmoid')
    max_pool_count = layer_plan.count('max_pool')
    avg_pool_count = layer_plan.count('avg_pool')
    total_layers = len(layer_plan) + len(hidden_dense_units) + 2  # flatten + output
    summary = f'{conv_count} conv, {relu_count} relu, {sigmoid_count} sigmoid, {max_pool_count} max-pool, {avg_pool_count} avg-pool, {len(hidden_dense_units)} hidden dense'
    return total_layers, summary

for spec in MODEL_SPECS:
    spec['total_layers'], spec['summary'] = summarize_plan(
        spec['layer_plan'],
        spec.get('hidden_dense_units', HIDDEN_DENSE_UNITS),
    )

pd.DataFrame([{
    'id': spec['id'],
    'label': spec['label'],
    'total_layers': spec['total_layers'],
    'conv_kernels': spec['filters'],
    'hidden_dense_units': ' -> '.join(map(str, spec.get('hidden_dense_units', HIDDEN_DENSE_UNITS))),
    'summary': spec['summary'],
    'layer_plan': ' -> '.join(spec['layer_plan']) + ' -> flatten -> ' + ' -> '.join([
        f'dense_{idx + 1}' for idx in range(len(spec.get('hidden_dense_units', HIDDEN_DENSE_UNITS)))
    ]) + ' -> output',
} for spec in MODEL_SPECS])

,id,label,total_layers,conv_kernels,hidden_dense_units,summary,layer_plan
0,compact-7,Compact 9-layer,9,6,16 -> 8,"2 conv, 1 relu, 1 sigmoid, 0 max-pool, 1 avg-p...",conv -> avg_pool -> sigmoid -> conv -> relu ->...
1,balanced-12,Balanced 14-layer,14,10,16 -> 8,"4 conv, 2 relu, 2 sigmoid, 1 max-pool, 1 avg-p...",conv -> avg_pool -> sigmoid -> conv -> relu ->...
2,deep-17,Deep 19-layer,19,14,16 -> 8,"6 conv, 3 relu, 3 sigmoid, 1 max-pool, 2 avg-p...",conv -> avg_pool -> sigmoid -> conv -> relu ->...

In [ ]:
SUPPORTED_LAYERS = {'conv', 'relu', 'sigmoid', 'max_pool', 'avg_pool'}

# Task 3 at lines 502-531: build a CNN directly from a layer plan so changing
# the order of conv / relu / max-pool produces a different trained demo model.
def build_configurable_cnn(
    layer_plan,
    filters=FILTERS,
    num_class=NUM_CLASS,
    hidden_dense_units=HIDDEN_DENSE_UNITS,
):
    unknown = [layer for layer in layer_plan if layer not in SUPPORTED_LAYERS]
    if unknown:
        raise ValueError(f'Unsupported layer types: {unknown}')

    layers = []
    block_index = 1
    conv_in_block = 0
    relu_in_block = 0
    sigmoid_in_block = 0

    for idx, layer_type in enumerate(layer_plan):
        first_layer_kwargs = {'input_shape': (WIDTH, HEIGHT, 3)} if idx == 0 else {}

        if layer_type == 'conv':
            conv_in_block += 1
            layers.append(
                Conv2D(filters, (3, 3), name=f'conv_{block_index}_{conv_in_block}', **first_layer_kwargs)
            )
        elif layer_type == 'relu':
            relu_in_block += 1
            layers.append(
                Activation('relu', name=f'relu_{block_index}_{relu_in_block}', **first_layer_kwargs)
            )
        elif layer_type == 'sigmoid':
            sigmoid_in_block += 1
            layers.append(
                Activation('sigmoid', name=f'sigmoid_{block_index}_{sigmoid_in_block}', **first_layer_kwargs)
            )
        elif layer_type == 'max_pool':
            layers.append(
                MaxPool2D((2, 2), name=f'max_pool_{block_index}', **first_layer_kwargs)
            )
            block_index += 1
            conv_in_block = 0
            relu_in_block = 0
            sigmoid_in_block = 0
        elif layer_type == 'avg_pool':
            layers.append(
                AveragePooling2D((2, 2), name=f'avg_pool_{block_index}', **first_layer_kwargs)
            )
            block_index += 1
            conv_in_block = 0
            relu_in_block = 0
            sigmoid_in_block = 0

    layers.append(Flatten(name='flatten'))

    for dense_index, units in enumerate(hidden_dense_units, start=1):
        layers.append(Dense(units, activation='relu', name=f'dense_{dense_index}'))

    layers.append(Dense(num_class, activation='softmax', name='output'))
    return Sequential(layers)

## Train All Architectures

This cell loops over the three architecture specs, trains each model, saves the best checkpoint, and records evaluation results.

In [ ]:
trained_models = {}
training_runs = []

# Task 3 at lines 2076-2141: train each planned architecture so the frontend
# can switch among multiple real networks instead of one fixed demo model.
for spec in MODEL_SPECS:
    tf.keras.backend.clear_session()

    model_dir = MODEL_ROOT / spec['id']
    model_dir.mkdir(parents=True, exist_ok=True)
    best_model_h5 = model_dir / 'best.h5'
    final_model_h5 = model_dir / 'final.h5'

    # Task 6.1: each model can use a different number of convolution kernels.
    model = build_configurable_cnn(
        spec['layer_plan'],
        filters=spec.get('filters', FILTERS),
        hidden_dense_units=spec.get('hidden_dense_units', HIDDEN_DENSE_UNITS),
    )
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=LR),
        loss='categorical_crossentropy',
        metrics=['categorical_accuracy'],
    )

    print('=' * 100)
    print(spec['label'])
    print('Layer plan:', spec['layer_plan'] + ['flatten'] + [
        f'dense_{idx + 1}' for idx in range(len(spec.get('hidden_dense_units', HIDDEN_DENSE_UNITS)))
    ] + ['output'])
    print('Convolution kernels per conv layer:', spec.get('filters', FILTERS))
    print('Hidden dense units:', spec.get('hidden_dense_units', HIDDEN_DENSE_UNITS))
    model.summary()

    callbacks = [
        EarlyStopping(
            monitor='val_loss',
            patience=PATIENCE,
            restore_best_weights=True,
            verbose=1,
        ),
        ModelCheckpoint(
            filepath=str(best_model_h5),
            monitor='val_loss',
            save_best_only=True,
            verbose=1,
        ),
    ]

    start_time = time()
    history = model.fit(
        train_dataset,
        validation_data=val_dataset,
        epochs=EPOCHS,
        callbacks=callbacks,
        verbose=1,
    )
    elapsed_minutes = (time() - start_time) / 60

    if best_model_h5.exists():
        model = tf.keras.models.load_model(best_model_h5)

    model.save(final_model_h5)
    test_loss, test_acc = model.evaluate(test_dataset, verbose=1)

    trained_models[spec['id']] = model
    training_runs.append({
        'id': spec['id'],
        'label': spec['label'],
        'total_layers': spec['total_layers'],
        'summary': spec['summary'],
        'conv_kernels': spec.get('filters', FILTERS),
        'hidden_dense_units': spec.get('hidden_dense_units', HIDDEN_DENSE_UNITS),
        'train_minutes': round(elapsed_minutes, 2),
        'test_loss': float(test_loss),
        'test_accuracy': float(test_acc),
        'best_model_h5': str(best_model_h5),
        'final_model_h5': str(final_model_h5),
        'layer_names': [layer.name for layer in model.layers],
    })

summary_df = pd.DataFrame(training_runs).sort_values('total_layers')
summary_df

/usr/local/lib/python3.12/dist-packages/keras/src/layers/convolutional/base_conv.py:113: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

====================================================================================================
Compact 9-layer
Layer plan: ['conv', 'avg_pool', 'sigmoid', 'conv', 'relu', 'flatten', 'dense_1', 'dense_2', 'output']
Convolution kernels per conv layer: 6
Hidden dense units: [16, 8]

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv_1_1 (Conv2D)               │ (None, 62, 62, 6)      │           168 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ avg_pool_1 (AveragePooling2D)   │ (None, 31, 31, 6)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ sigmoid_2_1 (Activation)        │ (None, 31, 31, 6)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_2_1 (Conv2D)               │ (None, 29, 29, 6)      │           330 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ relu_2_1 (Activation)           │ (None, 29, 29, 6)      │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 5046)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │        80,752 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output (Dense)                  │ (None, 10)             │            90 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 81,476 (318.27 KB)

 Trainable params: 81,476 (318.27 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/25
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 143ms/step - categorical_accuracy: 0.1079 - loss: 2.3033
Epoch 1: val_loss improved from None to 2.28989, saving model to /content/tiny-vgg/trained_models/compact-7/best.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 1: finished saving model to /content/tiny-vgg/trained_models/compact-7/best.h5
79/79 ━━━━━━━━━━━━━━━━━━━━ 20s 164ms/step - categorical_accuracy: 0.1070 - loss: 2.3006 - val_categorical_accuracy: 0.1320 - val_loss: 2.2899
Epoch 2/25
73/79 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - categorical_accuracy: 0.1249 - loss: 2.2934
Epoch 2: val_loss improved from 2.28989 to 2.25825, saving model to /content/tiny-vgg/trained_models/compact-7/best.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 2: finished saving model to /content/tiny-vgg/trained_models/compact-7/best.h5
79/79 ━━━━━━━━━━━━━━━━━━━━ 13s 133ms/step - categorical_accuracy: 0.1352 - loss: 2.2895 - val_categorical_accuracy: 0.1920 - val_loss: 2.2583
Epoch 3/25
74/79 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - categorical_accuracy: 0.1579 - loss: 2.2590
Epoch 3: val_loss improved from 2.25825 to 2.15900, saving model to /content/tiny-vgg/trained_models/compact-7/best.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 3: finished saving model to /content/tiny-vgg/trained_models/compact-7/best.h5
79/79 ━━━━━━━━━━━━━━━━━━━━ 13s 131ms/step - categorical_accuracy: 0.1642 - loss: 2.2299 - val_categorical_accuracy: 0.1920 - val_loss: 2.1590
Epoch 4/25
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 121ms/step - categorical_accuracy: 0.1920 - loss: 2.1370
Epoch 4: val_loss improved from 2.15900 to 2.02838, saving model to /content/tiny-vgg/trained_models/compact-7/best.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 4: finished saving model to /content/tiny-vgg/trained_models/compact-7/best.h5
79/79 ━━━━━━━━━━━━━━━━━━━━ 13s 138ms/step - categorical_accuracy: 0.2096 - loss: 2.1103 - val_categorical_accuracy: 0.2840 - val_loss: 2.0284
Epoch 5/25
71/79 ━━━━━━━━━━━━━━━━━━━━ 1s 132ms/step - categorical_accuracy: 0.2569 - loss: 2.0225
Epoch 5: val_loss improved from 2.02838 to 1.97797, saving model to /content/tiny-vgg/trained_models/compact-7/best.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 5: finished saving model to /content/tiny-vgg/trained_models/compact-7/best.h5
79/79 ━━━━━━━━━━━━━━━━━━━━ 13s 136ms/step - categorical_accuracy: 0.2626 - loss: 1.9960 - val_categorical_accuracy: 0.2720 - val_loss: 1.9780
Epoch 6/25
71/79 ━━━━━━━━━━━━━━━━━━━━ 1s 127ms/step - categorical_accuracy: 0.2920 - loss: 1.9304
Epoch 6: val_loss improved from 1.97797 to 1.92767, saving model to /content/tiny-vgg/trained_models/compact-7/best.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 6: finished saving model to /content/tiny-vgg/trained_models/compact-7/best.h5
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 124ms/step - categorical_accuracy: 0.2918 - loss: 1.9066 - val_categorical_accuracy: 0.3000 - val_loss: 1.9277
Epoch 7/25
75/79 ━━━━━━━━━━━━━━━━━━━━ 0s 118ms/step - categorical_accuracy: 0.3199 - loss: 1.8225
Epoch 7: val_loss did not improve from 1.92767
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 121ms/step - categorical_accuracy: 0.3246 - loss: 1.8110 - val_categorical_accuracy: 0.3080 - val_loss: 1.9675
Epoch 8/25
74/79 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - categorical_accuracy: 0.3532 - loss: 1.7712
Epoch 8: val_loss improved from 1.92767 to 1.81438, saving model to /content/tiny-vgg/trained_models/compact-7/best.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 8: finished saving model to /content/tiny-vgg/trained_models/compact-7/best.h5
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 119ms/step - categorical_accuracy: 0.3692 - loss: 1.7362 - val_categorical_accuracy: 0.3480 - val_loss: 1.8144
Epoch 9/25
74/79 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - categorical_accuracy: 0.3848 - loss: 1.6925
Epoch 9: val_loss improved from 1.81438 to 1.78951, saving model to /content/tiny-vgg/trained_models/compact-7/best.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 9: finished saving model to /content/tiny-vgg/trained_models/compact-7/best.h5
79/79 ━━━━━━━━━━━━━━━━━━━━ 21s 131ms/step - categorical_accuracy: 0.3874 - loss: 1.6786 - val_categorical_accuracy: 0.3440 - val_loss: 1.7895
Epoch 10/25
74/79 ━━━━━━━━━━━━━━━━━━━━ 0s 131ms/step - categorical_accuracy: 0.4126 - loss: 1.6313
Epoch 10: val_loss improved from 1.78951 to 1.70710, saving model to /content/tiny-vgg/trained_models/compact-7/best.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 10: finished saving model to /content/tiny-vgg/trained_models/compact-7/best.h5
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 130ms/step - categorical_accuracy: 0.4160 - loss: 1.6169 - val_categorical_accuracy: 0.4120 - val_loss: 1.7071
Epoch 11/25
74/79 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - categorical_accuracy: 0.4365 - loss: 1.5672
Epoch 11: val_loss did not improve from 1.70710
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 129ms/step - categorical_accuracy: 0.4252 - loss: 1.5870 - val_categorical_accuracy: 0.3800 - val_loss: 1.7332
Epoch 12/25
71/79 ━━━━━━━━━━━━━━━━━━━━ 1s 134ms/step - categorical_accuracy: 0.4235 - loss: 1.5570
Epoch 12: val_loss improved from 1.70710 to 1.69980, saving model to /content/tiny-vgg/trained_models/compact-7/best.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 12: finished saving model to /content/tiny-vgg/trained_models/compact-7/best.h5
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 130ms/step - categorical_accuracy: 0.4328 - loss: 1.5588 - val_categorical_accuracy: 0.4040 - val_loss: 1.6998
Epoch 13/25
77/79 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - categorical_accuracy: 0.4280 - loss: 1.5643
Epoch 13: val_loss did not improve from 1.69980
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 126ms/step - categorical_accuracy: 0.4386 - loss: 1.5464 - val_categorical_accuracy: 0.4200 - val_loss: 1.7025
Epoch 14/25
74/79 ━━━━━━━━━━━━━━━━━━━━ 0s 119ms/step - categorical_accuracy: 0.4543 - loss: 1.5183
Epoch 14: val_loss improved from 1.69980 to 1.68255, saving model to /content/tiny-vgg/trained_models/compact-7/best.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 14: finished saving model to /content/tiny-vgg/trained_models/compact-7/best.h5
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 122ms/step - categorical_accuracy: 0.4554 - loss: 1.5058 - val_categorical_accuracy: 0.3760 - val_loss: 1.6826
Epoch 15/25
74/79 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - categorical_accuracy: 0.4541 - loss: 1.5127
Epoch 15: val_loss improved from 1.68255 to 1.66403, saving model to /content/tiny-vgg/trained_models/compact-7/best.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 15: finished saving model to /content/tiny-vgg/trained_models/compact-7/best.h5
79/79 ━━━━━━━━━━━━━━━━━━━━ 21s 130ms/step - categorical_accuracy: 0.4634 - loss: 1.4907 - val_categorical_accuracy: 0.3680 - val_loss: 1.6640
Epoch 16/25
74/79 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - categorical_accuracy: 0.4604 - loss: 1.4587
Epoch 16: val_loss improved from 1.66403 to 1.64163, saving model to /content/tiny-vgg/trained_models/compact-7/best.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 16: finished saving model to /content/tiny-vgg/trained_models/compact-7/best.h5
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 129ms/step - categorical_accuracy: 0.4710 - loss: 1.4678 - val_categorical_accuracy: 0.4160 - val_loss: 1.6416
Epoch 17/25
73/79 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - categorical_accuracy: 0.4876 - loss: 1.4366
Epoch 17: val_loss did not improve from 1.64163
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 129ms/step - categorical_accuracy: 0.4776 - loss: 1.4456 - val_categorical_accuracy: 0.3720 - val_loss: 1.6988
Epoch 18/25
73/79 ━━━━━━━━━━━━━━━━━━━━ 0s 132ms/step - categorical_accuracy: 0.4797 - loss: 1.4256
Epoch 18: val_loss did not improve from 1.64163
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 129ms/step - categorical_accuracy: 0.4814 - loss: 1.4407 - val_categorical_accuracy: 0.4240 - val_loss: 1.6654
Epoch 19/25
71/79 ━━━━━━━━━━━━━━━━━━━━ 1s 133ms/step - categorical_accuracy: 0.4775 - loss: 1.4290
Epoch 19: val_loss did not improve from 1.64163
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 129ms/step - categorical_accuracy: 0.4886 - loss: 1.4181 - val_categorical_accuracy: 0.4240 - val_loss: 1.7259
Epoch 20/25
74/79 ━━━━━━━━━━━━━━━━━━━━ 0s 129ms/step - categorical_accuracy: 0.4914 - loss: 1.4307
Epoch 20: val_loss did not improve from 1.64163
79/79 ━━━━━━━━━━━━━━━━━━━━ 21s 129ms/step - categorical_accuracy: 0.4986 - loss: 1.3946 - val_categorical_accuracy: 0.3960 - val_loss: 1.6787
Epoch 21/25
74/79 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - categorical_accuracy: 0.4909 - loss: 1.4250
Epoch 21: val_loss improved from 1.64163 to 1.62735, saving model to /content/tiny-vgg/trained_models/compact-7/best.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 21: finished saving model to /content/tiny-vgg/trained_models/compact-7/best.h5
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 129ms/step - categorical_accuracy: 0.4998 - loss: 1.3896 - val_categorical_accuracy: 0.4320 - val_loss: 1.6273
Epoch 22/25
71/79 ━━━━━━━━━━━━━━━━━━━━ 1s 135ms/step - categorical_accuracy: 0.5031 - loss: 1.3777
Epoch 22: val_loss did not improve from 1.62735
79/79 ━━━━━━━━━━━━━━━━━━━━ 20s 129ms/step - categorical_accuracy: 0.5154 - loss: 1.3603 - val_categorical_accuracy: 0.4240 - val_loss: 1.6411
Epoch 23/25
72/79 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - categorical_accuracy: 0.5354 - loss: 1.3499
Epoch 23: val_loss did not improve from 1.62735
79/79 ━━━━━━━━━━━━━━━━━━━━ 13s 134ms/step - categorical_accuracy: 0.5208 - loss: 1.3563 - val_categorical_accuracy: 0.4160 - val_loss: 1.6521
Epoch 24/25
71/79 ━━━━━━━━━━━━━━━━━━━━ 1s 129ms/step - categorical_accuracy: 0.5217 - loss: 1.3340
Epoch 24: val_loss did not improve from 1.62735
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 126ms/step - categorical_accuracy: 0.5212 - loss: 1.3431 - val_categorical_accuracy: 0.4240 - val_loss: 1.6805
Epoch 25/25
72/79 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - categorical_accuracy: 0.5308 - loss: 1.3132
Epoch 25: val_loss did not improve from 1.62735
79/79 ━━━━━━━━━━━━━━━━━━━━ 13s 128ms/step - categorical_accuracy: 0.5304 - loss: 1.3178 - val_categorical_accuracy: 0.3880 - val_loss: 1.6502
Restoring model weights from the end of the best epoch: 21.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

4/4 ━━━━━━━━━━━━━━━━━━━━ 2s 198ms/step - categorical_accuracy: 0.4720 - loss: 1.5812
====================================================================================================
Balanced 14-layer
Layer plan: ['conv', 'avg_pool', 'sigmoid', 'conv', 'relu', 'conv', 'sigmoid', 'max_pool', 'conv', 'relu', 'flatten', 'dense_1', 'dense_2', 'output']
Convolution kernels per conv layer: 10
Hidden dense units: [16, 8]

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv_1_1 (Conv2D)               │ (None, 62, 62, 10)     │           280 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ avg_pool_1 (AveragePooling2D)   │ (None, 31, 31, 10)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ sigmoid_2_1 (Activation)        │ (None, 31, 31, 10)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_2_1 (Conv2D)               │ (None, 29, 29, 10)     │           910 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ relu_2_1 (Activation)           │ (None, 29, 29, 10)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_2_2 (Conv2D)               │ (None, 27, 27, 10)     │           910 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ sigmoid_2_2 (Activation)        │ (None, 27, 27, 10)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pool_2 (MaxPooling2D)       │ (None, 13, 13, 10)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_3_1 (Conv2D)               │ (None, 11, 11, 10)     │           910 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ relu_3_1 (Activation)           │ (None, 11, 11, 10)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 1210)           │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │        19,376 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output (Dense)                  │ (None, 10)             │            90 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 22,612 (88.33 KB)

 Trainable params: 22,612 (88.33 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/25
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 151ms/step - categorical_accuracy: 0.0983 - loss: 2.3089
Epoch 1: val_loss improved from None to 2.30311, saving model to /content/tiny-vgg/trained_models/balanced-12/best.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 1: finished saving model to /content/tiny-vgg/trained_models/balanced-12/best.h5
79/79 ━━━━━━━━━━━━━━━━━━━━ 20s 176ms/step - categorical_accuracy: 0.0952 - loss: 2.3044 - val_categorical_accuracy: 0.0920 - val_loss: 2.3031
Epoch 2/25
72/79 ━━━━━━━━━━━━━━━━━━━━ 0s 134ms/step - categorical_accuracy: 0.0984 - loss: 2.3027
Epoch 2: val_loss improved from 2.30311 to 2.30291, saving model to /content/tiny-vgg/trained_models/balanced-12/best.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 2: finished saving model to /content/tiny-vgg/trained_models/balanced-12/best.h5
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 130ms/step - categorical_accuracy: 0.0978 - loss: 2.3027 - val_categorical_accuracy: 0.1080 - val_loss: 2.3029
Epoch 3/25
71/79 ━━━━━━━━━━━━━━━━━━━━ 1s 138ms/step - categorical_accuracy: 0.1046 - loss: 2.3026
Epoch 3: val_loss improved from 2.30291 to 2.30287, saving model to /content/tiny-vgg/trained_models/balanced-12/best.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 3: finished saving model to /content/tiny-vgg/trained_models/balanced-12/best.h5
79/79 ━━━━━━━━━━━━━━━━━━━━ 13s 133ms/step - categorical_accuracy: 0.0938 - loss: 2.3027 - val_categorical_accuracy: 0.0920 - val_loss: 2.3029
Epoch 4/25
71/79 ━━━━━━━━━━━━━━━━━━━━ 1s 138ms/step - categorical_accuracy: 0.0948 - loss: 2.3027
Epoch 4: val_loss improved from 2.30287 to 2.30256, saving model to /content/tiny-vgg/trained_models/balanced-12/best.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 4: finished saving model to /content/tiny-vgg/trained_models/balanced-12/best.h5
79/79 ━━━━━━━━━━━━━━━━━━━━ 13s 132ms/step - categorical_accuracy: 0.0934 - loss: 2.3028 - val_categorical_accuracy: 0.1200 - val_loss: 2.3026
Epoch 5/25
71/79 ━━━━━━━━━━━━━━━━━━━━ 1s 138ms/step - categorical_accuracy: 0.1067 - loss: 2.3027
Epoch 5: val_loss improved from 2.30256 to 2.30253, saving model to /content/tiny-vgg/trained_models/balanced-12/best.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 5: finished saving model to /content/tiny-vgg/trained_models/balanced-12/best.h5
79/79 ━━━━━━━━━━━━━━━━━━━━ 13s 132ms/step - categorical_accuracy: 0.1000 - loss: 2.3028 - val_categorical_accuracy: 0.0840 - val_loss: 2.3025
Epoch 6/25
71/79 ━━━━━━━━━━━━━━━━━━━━ 1s 129ms/step - categorical_accuracy: 0.0986 - loss: 2.3026
Epoch 6: val_loss did not improve from 2.30253
79/79 ━━━━━━━━━━━━━━━━━━━━ 20s 124ms/step - categorical_accuracy: 0.0910 - loss: 2.3027 - val_categorical_accuracy: 0.1080 - val_loss: 2.3026
Epoch 7/25
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - categorical_accuracy: 0.0947 - loss: 2.3026
Epoch 7: val_loss did not improve from 2.30253
79/79 ━━━━━━━━━━━━━━━━━━━━ 13s 128ms/step - categorical_accuracy: 0.0964 - loss: 2.3027 - val_categorical_accuracy: 0.0800 - val_loss: 2.3027
Epoch 8/25
71/79 ━━━━━━━━━━━━━━━━━━━━ 1s 138ms/step - categorical_accuracy: 0.0888 - loss: 2.3027
Epoch 8: val_loss did not improve from 2.30253
79/79 ━━━━━━━━━━━━━━━━━━━━ 13s 132ms/step - categorical_accuracy: 0.0852 - loss: 2.3027 - val_categorical_accuracy: 0.1160 - val_loss: 2.3026
Epoch 9/25
71/79 ━━━━━━━━━━━━━━━━━━━━ 1s 134ms/step - categorical_accuracy: 0.1008 - loss: 2.3026
Epoch 9: val_loss did not improve from 2.30253
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 128ms/step - categorical_accuracy: 0.0956 - loss: 2.3028 - val_categorical_accuracy: 0.0840 - val_loss: 2.3027
Epoch 10/25
72/79 ━━━━━━━━━━━━━━━━━━━━ 0s 135ms/step - categorical_accuracy: 0.1018 - loss: 2.3027
Epoch 10: val_loss did not improve from 2.30253
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 130ms/step - categorical_accuracy: 0.0978 - loss: 2.3027 - val_categorical_accuracy: 0.0840 - val_loss: 2.3028
Epoch 11/25
71/79 ━━━━━━━━━━━━━━━━━━━━ 1s 137ms/step - categorical_accuracy: 0.0912 - loss: 2.3027
Epoch 11: val_loss did not improve from 2.30253
79/79 ━━━━━━━━━━━━━━━━━━━━ 13s 131ms/step - categorical_accuracy: 0.0918 - loss: 2.3027 - val_categorical_accuracy: 0.1160 - val_loss: 2.3027
Epoch 12/25
71/79 ━━━━━━━━━━━━━━━━━━━━ 1s 136ms/step - categorical_accuracy: 0.0963 - loss: 2.3027
Epoch 12: val_loss did not improve from 2.30253
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 130ms/step - categorical_accuracy: 0.0956 - loss: 2.3028 - val_categorical_accuracy: 0.0840 - val_loss: 2.3028
Epoch 13/25
75/79 ━━━━━━━━━━━━━━━━━━━━ 0s 130ms/step - categorical_accuracy: 0.0947 - loss: 2.3027
Epoch 13: val_loss did not improve from 2.30253
79/79 ━━━━━━━━━━━━━━━━━━━━ 13s 132ms/step - categorical_accuracy: 0.0958 - loss: 2.3027 - val_categorical_accuracy: 0.0840 - val_loss: 2.3027
Epoch 13: early stopping
Restoring model weights from the end of the best epoch: 5.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 147ms/step - categorical_accuracy: 0.1160 - loss: 2.3026
====================================================================================================
Deep 19-layer
Layer plan: ['conv', 'avg_pool', 'sigmoid', 'conv', 'relu', 'conv', 'max_pool', 'sigmoid', 'conv', 'relu', 'conv', 'relu', 'conv', 'avg_pool', 'sigmoid', 'flatten', 'dense_1', 'dense_2', 'output']
Convolution kernels per conv layer: 14
Hidden dense units: [16, 8]

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ conv_1_1 (Conv2D)               │ (None, 62, 62, 14)     │           392 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ avg_pool_1 (AveragePooling2D)   │ (None, 31, 31, 14)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ sigmoid_2_1 (Activation)        │ (None, 31, 31, 14)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_2_1 (Conv2D)               │ (None, 29, 29, 14)     │         1,778 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ relu_2_1 (Activation)           │ (None, 29, 29, 14)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_2_2 (Conv2D)               │ (None, 27, 27, 14)     │         1,778 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ max_pool_2 (MaxPooling2D)       │ (None, 13, 13, 14)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ sigmoid_3_1 (Activation)        │ (None, 13, 13, 14)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_3_1 (Conv2D)               │ (None, 11, 11, 14)     │         1,778 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ relu_3_1 (Activation)           │ (None, 11, 11, 14)     │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_3_2 (Conv2D)               │ (None, 9, 9, 14)       │         1,778 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ relu_3_2 (Activation)           │ (None, 9, 9, 14)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ conv_3_3 (Conv2D)               │ (None, 7, 7, 14)       │         1,778 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ avg_pool_3 (AveragePooling2D)   │ (None, 3, 3, 14)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ sigmoid_4_1 (Activation)        │ (None, 3, 3, 14)       │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ flatten (Flatten)               │ (None, 126)            │             0 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 16)             │         2,032 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ (None, 8)              │           136 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ output (Dense)                  │ (None, 10)             │            90 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 11,540 (45.08 KB)

 Trainable params: 11,540 (45.08 KB)

 Non-trainable params: 0 (0.00 B)

Epoch 1/25
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 152ms/step - categorical_accuracy: 0.0988 - loss: 2.3103
Epoch 1: val_loss improved from None to 2.30230, saving model to /content/tiny-vgg/trained_models/deep-17/best.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 1: finished saving model to /content/tiny-vgg/trained_models/deep-17/best.h5
79/79 ━━━━━━━━━━━━━━━━━━━━ 21s 178ms/step - categorical_accuracy: 0.0968 - loss: 2.3063 - val_categorical_accuracy: 0.1200 - val_loss: 2.3023
Epoch 2/25
78/79 ━━━━━━━━━━━━━━━━━━━━ 0s 117ms/step - categorical_accuracy: 0.1014 - loss: 2.3028
Epoch 2: val_loss did not improve from 2.30230
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 123ms/step - categorical_accuracy: 0.1012 - loss: 2.3029 - val_categorical_accuracy: 0.1200 - val_loss: 2.3025
Epoch 3/25
77/79 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - categorical_accuracy: 0.0974 - loss: 2.3035
Epoch 3: val_loss improved from 2.30230 to 2.30224, saving model to /content/tiny-vgg/trained_models/deep-17/best.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 3: finished saving model to /content/tiny-vgg/trained_models/deep-17/best.h5
79/79 ━━━━━━━━━━━━━━━━━━━━ 13s 130ms/step - categorical_accuracy: 0.0966 - loss: 2.3036 - val_categorical_accuracy: 0.1080 - val_loss: 2.3022
Epoch 4/25
77/79 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - categorical_accuracy: 0.1029 - loss: 2.3031
Epoch 4: val_loss did not improve from 2.30224
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 130ms/step - categorical_accuracy: 0.1020 - loss: 2.3029 - val_categorical_accuracy: 0.0800 - val_loss: 2.3032
Epoch 5/25
77/79 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - categorical_accuracy: 0.0950 - loss: 2.3029
Epoch 5: val_loss did not improve from 2.30224
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 131ms/step - categorical_accuracy: 0.0984 - loss: 2.3028 - val_categorical_accuracy: 0.1000 - val_loss: 2.3030
Epoch 6/25
77/79 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - categorical_accuracy: 0.0883 - loss: 2.3032
Epoch 6: val_loss did not improve from 2.30224
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 130ms/step - categorical_accuracy: 0.0930 - loss: 2.3031 - val_categorical_accuracy: 0.0800 - val_loss: 2.3030
Epoch 7/25
75/79 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - categorical_accuracy: 0.0968 - loss: 2.3029
Epoch 7: val_loss improved from 2.30224 to 2.30068, saving model to /content/tiny-vgg/trained_models/deep-17/best.h5

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

Epoch 7: finished saving model to /content/tiny-vgg/trained_models/deep-17/best.h5
79/79 ━━━━━━━━━━━━━━━━━━━━ 21s 134ms/step - categorical_accuracy: 0.0958 - loss: 2.3031 - val_categorical_accuracy: 0.1080 - val_loss: 2.3007
Epoch 8/25
76/79 ━━━━━━━━━━━━━━━━━━━━ 0s 120ms/step - categorical_accuracy: 0.1090 - loss: 2.3026
Epoch 8: val_loss did not improve from 2.30068
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 125ms/step - categorical_accuracy: 0.1024 - loss: 2.3030 - val_categorical_accuracy: 0.0840 - val_loss: 2.3027
Epoch 9/25
76/79 ━━━━━━━━━━━━━━━━━━━━ 0s 116ms/step - categorical_accuracy: 0.1081 - loss: 2.3029
Epoch 9: val_loss did not improve from 2.30068
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 119ms/step - categorical_accuracy: 0.0994 - loss: 2.3029 - val_categorical_accuracy: 0.1000 - val_loss: 2.3031
Epoch 10/25
77/79 ━━━━━━━━━━━━━━━━━━━━ 0s 122ms/step - categorical_accuracy: 0.0998 - loss: 2.3029
Epoch 10: val_loss did not improve from 2.30068
79/79 ━━━━━━━━━━━━━━━━━━━━ 13s 127ms/step - categorical_accuracy: 0.1000 - loss: 2.3028 - val_categorical_accuracy: 0.1000 - val_loss: 2.3032
Epoch 11/25
79/79 ━━━━━━━━━━━━━━━━━━━━ 0s 123ms/step - categorical_accuracy: 0.0951 - loss: 2.3028
Epoch 11: val_loss did not improve from 2.30068
79/79 ━━━━━━━━━━━━━━━━━━━━ 13s 130ms/step - categorical_accuracy: 0.1000 - loss: 2.3028 - val_categorical_accuracy: 0.1000 - val_loss: 2.3030
Epoch 12/25
78/79 ━━━━━━━━━━━━━━━━━━━━ 0s 125ms/step - categorical_accuracy: 0.1041 - loss: 2.3025
Epoch 12: val_loss did not improve from 2.30068
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 130ms/step - categorical_accuracy: 0.1000 - loss: 2.3028 - val_categorical_accuracy: 0.1000 - val_loss: 2.3029
Epoch 13/25
77/79 ━━━━━━━━━━━━━━━━━━━━ 0s 127ms/step - categorical_accuracy: 0.1019 - loss: 2.3025
Epoch 13: val_loss did not improve from 2.30068
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 131ms/step - categorical_accuracy: 0.1000 - loss: 2.3027 - val_categorical_accuracy: 0.1000 - val_loss: 2.3030
Epoch 14/25
76/79 ━━━━━━━━━━━━━━━━━━━━ 0s 128ms/step - categorical_accuracy: 0.0972 - loss: 2.3027
Epoch 14: val_loss did not improve from 2.30068
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 130ms/step - categorical_accuracy: 0.0924 - loss: 2.3027 - val_categorical_accuracy: 0.0800 - val_loss: 2.3031
Epoch 15/25
78/79 ━━━━━━━━━━━━━━━━━━━━ 0s 126ms/step - categorical_accuracy: 0.1035 - loss: 2.3026
Epoch 15: val_loss did not improve from 2.30068
79/79 ━━━━━━━━━━━━━━━━━━━━ 12s 131ms/step - categorical_accuracy: 0.1000 - loss: 2.3027 - val_categorical_accuracy: 0.0800 - val_loss: 2.3031
Epoch 15: early stopping
Restoring model weights from the end of the best epoch: 7.

WARNING:absl:Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.
WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

4/4 ━━━━━━━━━━━━━━━━━━━━ 1s 148ms/step - categorical_accuracy: 0.0920 - loss: 2.3057

,id,label,total_layers,summary,conv_kernels,hidden_dense_units,train_minutes,test_loss,test_accuracy,best_model_h5,final_model_h5,layer_names
0,compact-7,Compact 9-layer,9,"2 conv, 1 relu, 1 sigmoid, 0 max-pool, 1 avg-p...",6,"[16, 8]",5.84,1.581247,0.472,/content/tiny-vgg/trained_models/compact-7/bes...,/content/tiny-vgg/trained_models/compact-7/fin...,"[conv_1_1, avg_pool_1, sigmoid_2_1, conv_2_1, ..."
1,balanced-12,Balanced 14-layer,14,"4 conv, 2 relu, 2 sigmoid, 1 max-pool, 1 avg-p...",10,"[16, 8]",2.96,2.302649,0.116,/content/tiny-vgg/trained_models/balanced-12/b...,/content/tiny-vgg/trained_models/balanced-12/f...,"[conv_1_1, avg_pool_1, sigmoid_2_1, conv_2_1, ..."
2,deep-17,Deep 19-layer,19,"6 conv, 3 relu, 3 sigmoid, 1 max-pool, 2 avg-p...",14,"[16, 8]",3.39,2.305742,0.092,/content/tiny-vgg/trained_models/deep-17/best.h5,/content/tiny-vgg/trained_models/deep-17/final.h5,"[conv_1_1, avg_pool_1, sigmoid_2_1, conv_2_1, ..."

## Export All Models to TensorFlow.js

This cell exports every trained model into its own folder and writes a minimal `model-index.json` file that the website can use for a dropdown selector.

The manifest intentionally stores only:

- `id`
- `label`
- `modelPath`

The website derives layer counts, summaries, visible layer lists, and stage boundaries by reading each selected `model.json` at runtime.

In [ ]:
import tensorflowjs as tfjs

manifest = []

for run in training_runs:
    export_dir = TFJS_ROOT / run['id']
    if export_dir.exists():
        shutil.rmtree(export_dir)
    export_dir.mkdir(parents=True, exist_ok=True)

    tfjs.converters.save_keras_model(trained_models[run['id']], str(export_dir))

    # Task 5: keep the selector manifest minimal. The website derives
    # total layers, summary, layer order, and stage boundaries from model.json.
    manifest.append({
        'id': run['id'],
        'label': run['label'],
        'modelPath': f"assets/data/models/{run['id']}/model.json",
    })

manifest_path = TFJS_ROOT / 'model-index.json'
with open(manifest_path, 'w') as f:
    json.dump(manifest, f, indent=2)

print('Export root:', TFJS_ROOT)
print('Manifest:', manifest_path)
print(json.dumps(manifest, indent=2))

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.
WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.
WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

failed to lookup keras version from the file,
    this is likely a weight only file
failed to lookup keras version from the file,
    this is likely a weight only file
failed to lookup keras version from the file,
    this is likely a weight only file
Export root: /content/tiny-vgg/frontend_models
Manifest: /content/tiny-vgg/frontend_models/model-index.json
[
  {
    "id": "compact-7",
    "label": "Compact 9-layer",
    "modelPath": "assets/data/models/compact-7/model.json"
  },
  {
    "id": "balanced-12",
    "label": "Balanced 14-layer",
    "modelPath": "assets/data/models/balanced-12/model.json"
  },
  {
    "id": "deep-17",
    "label": "Deep 19-layer",
    "modelPath": "assets/data/models/deep-17/model.json"
  }
]

In [ ]:
# Optional: bundle the exported frontend assets for download or copying to Drive
# Task 3 at lines 2305-2312: bundle the exported frontend-ready models so the
# website can demonstrate all three trained architectures from one copied folder.
bundle_dir = WORKDIR / 'frontend_bundle'
if bundle_dir.exists():
    shutil.rmtree(bundle_dir)
bundle_dir.mkdir(parents=True, exist_ok=True)

models_target = bundle_dir / 'models'
shutil.copytree(TFJS_ROOT, models_target)

zip_path = WORKDIR / 'cnn_explainer_multi_model_exports.zip'
if zip_path.exists():
    zip_path.unlink()
shutil.make_archive(str(zip_path.with_suffix('')), 'zip', bundle_dir)
print('Created bundle:', zip_path)

Created bundle: /content/tiny-vgg/cnn_explainer_multi_model_exports.zip

## Frontend Handoff

After training finishes, copy the exported files into the website repo using this structure:

```text
public/assets/data/
  model-index.json
  models/
    compact-7/
      model.json
      group1-shard1of1.bin
    balanced-12/
      model.json
      group1-shard1of1.bin
    deep-17/
      model.json
      group1-shard1of1.bin
```

Then the website can load the manifest, let the user choose a model, and redraw the layers based on the selected architecture.

## About `.bin`-only architecture reading

A TensorFlow.js `.bin` file is only a raw binary weight shard. It does **not** store layer order, layer names, tensor names, tensor shapes, activations, pooling sizes, or model topology. Therefore, the website cannot reconstruct the architecture from `.bin` alone.

The minimal correct input for architecture-driven rendering is:

- model folder path,
- `model.json`,
- referenced `.bin` shard(s).

The frontend should derive architecture information from `model.json`, and use `.bin` only for trained weight values.

In [ ]:
# Copy the bundled zip to Google Drive
from pathlib import Path
import shutil

zip_path = WORKDIR / 'cnn_explainer_multi_model_exports.zip'
drive_zip_path = DRIVE_PROJECT_DIR / 'cnn_explainer_multi_model_exports.zip'

if not zip_path.exists():
    raise FileNotFoundError(f'Missing bundle zip: {zip_path}')

shutil.copy2(zip_path, drive_zip_path)
print('Copied zip to Drive:', drive_zip_path)

Copied zip to Drive: /content/drive/MyDrive/CNN/cnn_explainer_multi_model_exports.zip